//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eThanhTra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DThanhTraThanhVienCongViecChiTiet
    {
        public long Id { get; set; }
        public Nullable<long> IdThanhTra { get; set; }
        public Nullable<long> IdThanhVien { get; set; }
        public Nullable<long> IdCongViec { get; set; }
        public Nullable<long> IdThanhVienCongViec { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NoiDung { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayNhatKy { get; set; }
    }
}
