//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eThanhTra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DThanhTraThanhVien
    {
        public long Id { get; set; }
        public Nullable<long> IdThanhTra { get; set; }
        public string UserName { get; set; }
        public string UserNameOld { get; set; }
        public Nullable<int> VaiTro { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string GhiChu { get; set; }
    }
}
