//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eThanhTra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DThanhTraTamDung
    {
        public int Id { get; set; }
        public string QuyetDinhTD { get; set; }
        public Nullable<long> IDThanhTra { get; set; }
        public int SoNgayTD { get; set; }
        public System.DateTime BatDauTD { get; set; }
        public System.DateTime KetThucTD { get; set; }
        public string LyDoTamDung { get; set; }
    
        public virtual DThanhTra DThanhTra { get; set; }
    }
}
