//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eThanhTra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DThanhTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DThanhTra()
        {
            this.DThanhTraCongViecs = new HashSet<DThanhTraCongViec>();
            this.DThanhTraThanhViens = new HashSet<DThanhTraThanhVien>();
            this.DThanhTraThanhVienCongViecs = new HashSet<DThanhTraThanhVienCongViec>();
            this.DThanhTraGiaHans = new HashSet<DThanhTraGiaHan>();
            this.DThanhTraTamDungs = new HashSet<DThanhTraTamDung>();
            this.DThanhTraKKVMs = new HashSet<DThanhTraKKVM>();
        }
    
        public long Id { get; set; }
        public string MST { get; set; }
        public string TenNNT { get; set; }
        public string MaCQT { get; set; }
        public string UserNameTDTT { get; set; }
        public Nullable<System.DateTime> NgayCongBo { get; set; }
        public Nullable<int> ThoiGian { get; set; }
        public Nullable<System.DateTime> HanKetThuc { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string CreatedUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DThanhTraCongViec> DThanhTraCongViecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DThanhTraThanhVien> DThanhTraThanhViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DThanhTraThanhVienCongViec> DThanhTraThanhVienCongViecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DThanhTraGiaHan> DThanhTraGiaHans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DThanhTraTamDung> DThanhTraTamDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DThanhTraKKVM> DThanhTraKKVMs { get; set; }
    }
}
