//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eThanhTra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DThanhTra : BaseDto
    {
        public long Id { get; set; }
        public string MST { get; set; }
        public string TenNNT { get; set; }
        public string MaCQT { get; set; }
        public string UserNameTDTT { get; set; }

        private Nullable<System.DateTime> _NgayCongBo;
        public Nullable<System.DateTime> NgayCongBo { get; set; }
        public Nullable<int> ThoiGian { get; set; }

        public Nullable<System.DateTime> HanKetThuc { get; set; }

        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string GhiChu { get; set; }
    }
}
