//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eThanhTra.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eThanhTraEntities : DbContext
    {
        public eThanhTraEntities()
            : base("name=eThanhTraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SCQT> SCQTs { get; set; }
        public virtual DbSet<SUser> SUsers { get; set; }
        public virtual DbSet<SUserCQT> SUserCQTs { get; set; }
        public virtual DbSet<DThanhTra> DThanhTras { get; set; }
        public virtual DbSet<DThanhTraCongViec> DThanhTraCongViecs { get; set; }
        public virtual DbSet<DThanhTraThanhVien> DThanhTraThanhViens { get; set; }
        public virtual DbSet<DThanhTraThanhVienCongViec> DThanhTraThanhVienCongViecs { get; set; }
        public virtual DbSet<DThanhTraThanhVienCongViecChiTiet> DThanhTraThanhVienCongViecChiTiets { get; set; }
        public virtual DbSet<DThanhTraQuyetDinh> DThanhTraQuyetDinhs { get; set; }
        public virtual DbSet<SLichLamViec> SLichLamViecs { get; set; }
        public virtual DbSet<SUserType> SUserTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<DGiaHanTT> DGiaHanTTs { get; set; }
    
        public virtual ObjectResult<PGetUserByMaCQT_Result> PGetUserByMaCQT(string maCQT)
        {
            var maCQTParameter = maCQT != null ?
                new ObjectParameter("MaCQT", maCQT) :
                new ObjectParameter("MaCQT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PGetUserByMaCQT_Result>("PGetUserByMaCQT", maCQTParameter);
        }
    
        public virtual ObjectResult<PGetCQTByMaCQT_Result> PGetCQTByMaCQT(string maCQT)
        {
            var maCQTParameter = maCQT != null ?
                new ObjectParameter("MaCQT", maCQT) :
                new ObjectParameter("MaCQT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PGetCQTByMaCQT_Result>("PGetCQTByMaCQT", maCQTParameter);
        }
    }
}
