//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eThanhTra.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLichLamViec
    {
        public int Id { get; set; }
        public Nullable<int> Nam { get; set; }
        public int Thang { get; set; }
        public int Ngay { get; set; }
        public int Loai { get; set; }
        public string NoiDung { get; set; }
    }
}
